import Link from "next/link";
import { useId } from "react";
import { STONE_FACETS, STONE_GROUND_Y } from "./stone-facets";

// The brand mark: a faceted white stone, generated by scripts/generate-stone.mjs.
export function StoneMark({ className = "" }: { className?: string }) {
  const shadowId = `stone-shadow-${useId().replace(/[^a-zA-Z0-9_-]/g, "")}`;
  return (
    <svg viewBox="0 0 40 40" className={className} aria-hidden>
      <defs>
        <radialGradient id={shadowId}>
          <stop offset="0" stopColor="#0f1012" stopOpacity="0.3" />
          <stop offset="1" stopColor="#0f1012" stopOpacity="0" />
        </radialGradient>
      </defs>
      <ellipse cx="20" cy={STONE_GROUND_Y} rx="15" ry="2.4" fill={`url(#${shadowId})`} />
      {/* Faint outline drawn under the facets so the pale stone holds its edge on light backgrounds. */}
      <g fill="none" stroke="#0f1012" strokeOpacity="0.14" strokeWidth="1.2" strokeLinejoin="round">
        {STONE_FACETS.map((f) => (
          <polygon key={f.points} points={f.points} />
        ))}
      </g>
      <g strokeLinejoin="round">
        {STONE_FACETS.map((f) => (
          <polygon key={f.points} points={f.points} fill={f.fill} stroke={f.fill} strokeWidth="0.35" />
        ))}
      </g>
    </svg>
  );
}

export function Logo({ onClick }: { onClick?: () => void }) {
  return (
    <Link
      href="/"
      onClick={onClick}
      className="group inline-flex items-center gap-2.5"
      aria-label="Whitestone Learning Network — home"
    >
      <StoneMark className="h-10 w-10 transition-transform duration-500 ease-out-soft group-hover:rotate-[-8deg] md:h-11 md:w-11" />
      <span className="text-[1.65rem] font-extrabold leading-none tracking-[-0.055em] md:text-[1.85rem]">
        whitestone
      </span>
    </Link>
  );
}
