// Generated by scripts/generate-stone.mjs (seed 107). Do not edit by hand.
export const STONE_FACETS: { points: string; fill: string }[] = [
  {
    "points": "30.08,8.80 32.17,11.36 37.00,20.76",
    "fill": "#aeb0b3"
  },
  {
    "points": "30.08,8.80 32.01,21.67 37.00,20.76",
    "fill": "#acaeb1"
  },
  {
    "points": "32.01,21.67 37.00,20.76 30.72,29.20",
    "fill": "#acaeb1"
  },
  {
    "points": "3.00,18.21 14.01,28.70 9.03,25.34",
    "fill": "#acaeb1"
  },
  {
    "points": "10.07,12.71 19.01,20.49 3.00,18.21",
    "fill": "#fdffff"
  },
  {
    "points": "30.08,8.80 10.07,12.71 19.01,20.49",
    "fill": "#fdffff"
  },
  {
    "points": "30.08,8.80 19.01,20.49 32.01,21.67",
    "fill": "#bbbdc0"
  },
  {
    "points": "19.01,20.49 32.01,21.67 30.72,29.20",
    "fill": "#b6b8bb"
  },
  {
    "points": "19.01,20.49 3.00,18.21 14.01,28.70",
    "fill": "#eef0f3"
  },
  {
    "points": "19.01,20.49 14.01,28.70 30.72,29.20",
    "fill": "#acaeb1"
  }
];

export const STONE_GROUND_Y = 29.8;
