// Generates the Whitestone stone mark: a low-poly white rock built from the
// convex hull of jittered points on a squashed sphere, lit from the top left
// and projected to flat polygons in a 40x40 box.
//
//   node scripts/generate-stone.mjs [seed]
//
// Writes src/components/stone-facets.ts (used by the logo and OG image) and
// src/app/icon.svg (favicon). Change the seed to get a different stone.
import fs from "node:fs";
import path from "node:path";

const SEED = Number(process.argv[2] ?? 107);
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");

function rng(seed) {
  let s = seed >>> 0;
  return () => (s = (s * 1664525 + 1013904223) >>> 0) / 4294967296;
}
const sub = (a, b) => [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
const cross = (a, b) => [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]];
const dot = (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
const unit = (a) => a.map((v) => v / Math.hypot(...a));

function makeStone(seed, { n = 12, sx = 1.4, sy = 0.8, sz = 1.05, jitter = 0.3, yaw = 0.5, pitch = 0.42 } = {}) {
  const r = rng(seed);
  let pts = [];
  for (let i = 0; i < n; i++) {
    const t = (i + 0.5) / n;
    const phi = Math.acos(1 - 2 * t);
    const th = Math.PI * (1 + Math.sqrt(5)) * i + r() * 0.9;
    const rad = 1 + (r() - 0.5) * 2 * jitter;
    const p = [Math.sin(phi) * Math.cos(th) * rad * sx, Math.cos(phi) * rad * sy, Math.sin(phi) * Math.sin(th) * rad * sz];
    if (p[1] < -0.5 * sy) p[1] = -0.5 * sy - r() * 0.06; // flatter base, as if resting on the ground
    pts.push(p);
  }

  // 3/4 view from slightly above.
  const [cy, syw, cp, sp] = [Math.cos(yaw), Math.sin(yaw), Math.cos(pitch), Math.sin(pitch)];
  pts = pts.map(([x, y, z]) => {
    const x1 = x * cy + z * syw;
    const z1 = -x * syw + z * cy;
    return [x1, y * cp - z1 * sp, y * sp + z1 * cp];
  });

  // Convex hull by brute force (n is tiny).
  const faces = [];
  for (let i = 0; i < n; i++)
    for (let j = i + 1; j < n; j++)
      for (let k = j + 1; k < n; k++) {
        const c = cross(sub(pts[j], pts[i]), sub(pts[k], pts[i]));
        if (Math.hypot(...c) < 1e-9) continue;
        let nrm = unit(c);
        let pos = 0;
        let neg = 0;
        for (let m = 0; m < n; m++) {
          if (m === i || m === j || m === k) continue;
          const d = dot(nrm, sub(pts[m], pts[i]));
          if (d > 1e-7) pos++;
          else if (d < -1e-7) neg++;
        }
        if (pos && neg) continue;
        if (pos) nrm = nrm.map((v) => -v);
        faces.push({ idx: [i, j, k], n: nrm });
      }

  const light = unit([-0.55, 0.75, 0.6]);
  const visible = faces
    .filter((f) => f.n[2] > 1e-4)
    .map((f) => {
      const lambert = Math.max(0, dot(f.n, light));
      const shade = Math.min(1, 0.36 + 0.64 * Math.pow(lambert, 0.85) + Math.max(0, f.n[1]) * 0.04);
      return { ...f, shade, depth: f.idx.reduce((s, i) => s + pts[i][2], 0) / 3 };
    })
    .sort((a, b) => a.depth - b.depth);

  const xs = pts.map((p) => p[0]);
  const ys = pts.map((p) => -p[1]);
  const [minX, maxX, minY, maxY] = [Math.min(...xs), Math.max(...xs), Math.min(...ys), Math.max(...ys)];
  const scale = Math.min(34 / (maxX - minX), 26 / (maxY - minY));
  const ox = 20 - ((minX + maxX) / 2) * scale;
  const oy = 19 - ((minY + maxY) / 2) * scale;
  const pt = (i) => `${(pts[i][0] * scale + ox).toFixed(2)},${(-pts[i][1] * scale + oy).toFixed(2)}`;
  const fill = (s) => {
    const g = Math.round(128 + 127 * s);
    return `#${[g - 2, g, Math.min(255, g + 3)].map((v) => v.toString(16).padStart(2, "0")).join("")}`;
  };

  return {
    facets: visible.map((f) => ({ points: f.idx.map(pt).join(" "), fill: fill(f.shade) })),
    groundY: +(((maxY - minY) / 2) * scale + 19 + 0.6).toFixed(2),
  };
}

const stone = makeStone(SEED);

fs.writeFileSync(
  path.join(root, "src/components/stone-facets.ts"),
  `// Generated by scripts/generate-stone.mjs (seed ${SEED}). Do not edit by hand.
export const STONE_FACETS: { points: string; fill: string }[] = ${JSON.stringify(stone.facets, null, 2)};

export const STONE_GROUND_Y = ${stone.groundY};
`,
);

const polys = (attrs) => stone.facets.map((f) => `<polygon points="${f.points}" ${attrs(f)}/>`).join("");
fs.writeFileSync(
  path.join(root, "src/app/icon.svg"),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><rect width="40" height="40" rx="10" fill="#0f1012"/><g transform="translate(20 20) scale(0.92) translate(-20 -20.5)" stroke-linejoin="round">${polys((f) => `fill="${f.fill}" stroke="${f.fill}" stroke-width=".4"`)}</g></svg>\n`,
);

console.log(`stone seed ${SEED}: ${stone.facets.length} facets`);
